# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flowizewscreate2911publicrepoapp02-docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ee00086977b34cdea89fa79770082d0d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c9448ac4c47a406fa00ab2c70f92663e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ee00086977b34cdea89fa79770082d0d }}/flowizewscreate2911publicrepoapp02tag:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flowizewscreate2911publicrepoapp02-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9b6e9f08275a45848b0c48bbf77b3261 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ee00086977b34cdea89fa79770082d0d }}/flowizewscreate2911publicrepoapp02tag:${{ github.sha }}'